cart/urls.py
from django.conf.urls import url
from . import views

app_name = 'cart'

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'

urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create')
]

shopOnlineApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'shoponline'
urlpatterns = [
    path('', views.index, name='index'),
    path('product_detail/<int:id>', views.product_detail, name='product_detail'),
]

shoponline/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from shopOnlineApp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shoponline/', include('shopOnlineApp.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('orders.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

orders/models.py
from django.db import models
from shopOnlineApp.models import Product


class Order(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    address = models.CharField(max_length=150)
    postal_code = models.CharField(max_length=30)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(
        Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(
        Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

shopOnlineApp/models.py
from django.db import models
# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=264,unique=True)
    fee = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to = "images" )

    def __str__( self ):
        return str( self .name)
    

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 26)]

class CartAddProductForm(forms.Form):
    quantity = forms.ChoiceField(choices=PRODUCT_QUANTITY_CHOICES, widget=forms.Select(attrs={'class':'form-control','style':'width: 90px; text-align:center'}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
	class Meta:
		model = Order
		fields = ['first_name', 'last_name', 'email', 'address', 'postal_code', 'city']

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)
		for field in self.Meta.fields:
			self.fields[field].widget.attrs.update({
				'class': 'form-control'
			})

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shopOnlineApp.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):

    # create a new cart object passing it the request object
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    if 'Th_don_gia' not in request.POST:
        price = 0
    else:
        price = request.POST['Th_don_gia']
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, price=price, quantity=int(
            cd['quantity']), update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Tivi, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    print('------------------------------------')
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'update': True})
        # print(item['update_quantity_form'])
    return render(request, 'cart/detail.html', {'cart': cart})

orders/views.py
from django.shortcuts import render
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from django.core.mail import EmailMessage

def order_create(request):
	cart = Cart(request)
	if request.method == 'POST':
		form = OrderCreateForm(request.POST)
		chuoi_don_hang='<table width="100%">'
		if form.is_valid():
			order = form.save()
			chuoi_don_hang+='<tr><td colspan="3">Đơn hàng của bạn # ' + str(order.id) + '</td></tr>'
			for item in cart:
				OrderItem.objects.create(
					order=order,
					product=item['product'],
					price=item['price'],
					quantity=item['quantity']
				)
				chuoi_don_hang+='<tr><td rowspan="4"><img src="http://127.0.0.1:8000'+item['product'].hinh_san_pham.url+'" width="250px"></td>'
				chuoi_don_hang+='<td>Sản phẩm</td><td>'+item['product'].ten_san_pham+'</td></tr>'
				chuoi_don_hang+='<tr><td>Tên shop</td><td>Trung tâm tin học</td></tr>'
				chuoi_don_hang+='<tr><td>Thanh toán</td><td>'+str(item['price']*item['quantity'])+'</td></tr>'
				chuoi_don_hang+='<tr><td>Người nhận</td><td>'+order.last_name +' ' + order.first_name +' '+order.postal_code 
				chuoi_don_hang+= '<br/>'+order.address+'</td></tr>'

			cart.clear()
			chuoi_don_hang+='</table>'
			email = EmailMessage('Xác nhận đơn hàng', chuoi_don_hang, to=[order.email]) 
			email.content_subtype = "html"
			print(email.send())
		return render(request, 'orders/order/created.html', {'order': chuoi_don_hang})
	else:
		form = OrderCreateForm()
	return render(request, 'orders/order/create.html', {'form': form})

shopOnlineApp/views.py
from django.shortcuts import render
from .models import Product
from cart.forms import CartAddProductForm

# Create your views here.


def index(request):
    prolist = Product.objects.order_by('name')
    context = {
        'products': prolist,
    }
    return render(request, 'shopOnlineApp/trangchu.html', context)


def product_detail(request, id=None):
    product_detail = Product.objects.get(pk=id)
    cart = CartAddProductForm()
    context = {
        'product_details': product_detail,
        'cart': cart,
    }
    return render(request, 'shopOnlineApp/product_detail.html', context)


def chi_tiet(request, id):
    sanpham = Tivi.objects.get(id=id)
    cart_product_form = CartAddProductForm()
    context = {
        'sanpham': sanpham,
        'cart_product_form': cart_product_form,
    }
    return render(reequest, 'Tivi_app/chi_tiet_san_pham.html', context)

templates/cart/detail.html
{% extends 'master.html' %}
{% load static %}
{% block title %}
Your Shopping Cart
{% endblock %}


{% block content %}
<div class="container">
    <div class="row" style="margin-top: 6%">
        <h2>Your Shopping Cart
            <span class="badge pull-right">
                {% with totail_items=cart|length %}
                {% if cart|length > 0 %}
                My Shopping Order:
                <a href="{% url "cart:cart_detail" %}">
                    {{ totail_items }} item {{ totail_items|pluralize }}, Kshs. {{ cart.get_total_price }}
                </a>
                {% else %}
                Your cart is empty.
                {% endif %}
                {% endwith %}
            </span>
        </h2>
        <table class="table table-striped table-hover">
            <thead style="background-color: #5AC8FA">
                <tr>
                    <th>Image</th>
                    <th>Product</th>
                    <th>Quantity</th>
                    <th>Remove</th>
                    <th>Unit Price</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for item in cart %}
                {% with product=item.product  %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="{% static 'hinh' %}/{{product.Ma_so}}.jpg" alt="..."
                                style="height: 130px; width: auto">
                        </a>
                    </td>
                    <td>{{ product.Ten }}</td>
                    <td>
                        <form class="form-inline" action="{% url "cart:cart_add" product.id %}" method="post">
                            {% csrf_token %}
                            {{ item.update_quantity_form.quantity }}
                            {{ item.update_quantity_form.update }}
                            <input type="submit" value="Update" class="btn btn-info">
                        </form>
                    </td>
                    <td>
                        <a href="{% url "cart:cart_remove" product.id %}">Remove</a>
                    </td>
                    <td>kshs. {{ item.price }}</td>
                    <td>kshs. {{ item.total_price }}</td>
                </tr>
                {% endwith %}
                {% endfor %}
                <tr style="background-color: #5AC8FA">
                    <td><b>Total</b></td>
                    <td colspan="4"></td>
                    <td colspan="num"><b>kshs. {{ cart.get_total_price }}</b></td>
                </tr>
            </tbody>
        </table>
        <p class="text-right">
            <a href="{% url "orders:order_create" %}" class="btn btn-primary">Checkout</a>
        </p>
    </div>
</div>
{% endblock %}

templates/cart/index.html
<html>
<head><title></title></head>

<body>

{{ content }}

</body>
</html>

templates/master.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Heroic Features - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'shoponline/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'shoponline/css/heroic-features.css' %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'shoponline:index' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Contact</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}

    {% endblock %}
    
    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'shoponline/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'shoponline/vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'shoponline/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

  </body>

</html>

templates/orders/index.html
<html>
<head><title></title></head>

<body>

{{ content }}

</body>
</html>

templates/orders/order/create.html
{% extends "layout.html" %}
{% load i18n static %}
{% load humanize %}
{% block head %}
	<head>
	<title>Category</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="Tech Mag template project">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css_js/styles/bootstrap-4.1.2/bootstrap.min.css'%}">
	<link href="{% static 'css_js/plugins/font-awesome-4.7.0/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="{% static 'css_js/styles/category.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css_js/styles/category_responsive.css'%}">
	</head>
{% endblock %}
{% block slider %}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8">
                <h4 class="page-header">Checkout</h4>
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form.as_p }}<br>
                    <input type="submit" class="btn btn-primary" value="Submit order">
                </form>
            </div>
            <div class="col-md-4">
                <div class="page-header">
                    Your Order
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                        <li class="list-group-item">
                        {{ item.quantity }}x {{ item.product.name }}
                        <span>Kshs. {{ item.total_price }}</span>
                        </li>
                    {% endfor %}

                <li class="list-group-item active">Total Cost: kshs. {{ cart.get_total_price }}</li>
                </ul>

            </div>
        </div>
    </div>
{% endblock %}

templates/orders/order/created.html
{% extends "layout.html" %}
{% load i18n static %}
{% load humanize %}
{% block head %}
	<head>
	<title>Category</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="description" content="Tech Mag template project">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static 'css_js/styles/bootstrap-4.1.2/bootstrap.min.css'%}">
	<link href="{% static 'css_js/plugins/font-awesome-4.7.0/css/font-awesome.min.css'%}" rel="stylesheet" type="text/css">
	<link rel="stylesheet" type="text/css" href="{% static 'css_js/styles/category.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css_js/styles/category_responsive.css'%}">
	</head>
{% endblock %}
{% block slider %}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <h3 class="page-header">Thank You For Shopping With Us
                </h3>
				{% autoescape off %}{{ order }}{% endautoescape %}
            </div>
        </div>
    </div>
{% endblock %}

templates/shopOnlineApp/product_detail.html
{% extends "master.html" %}
{% block content %}
{% load staticfiles %}
<div class='row text-center'>
    {% if product_details %}
    <div class='container'>
        <div class='card thumbnail'>
            <img class='img-responsive' src='{{product_details.image.url}}' alt='{{product_details.name}}' width='350'
                height='350' />
            <div class='card-body'>
                <h4 class='card-title'>{{product_details.name}}</h4>
                <p class='card-text'>{{product_details.description}}<br />{{product_details.fee}} vnđ</p>
            </div>
            <form action="{% url 'cart:cart_add' product_details.id %}" method="post">
                {% csrf_token %}
                <div class="form-inline">
                    <label>
                        <input type="radio" name="Th_don_gia" value="{{product_details.fee}}" checked /> size s
                        {{product_details.fee}}
                    </label>
                </div>
                <div class="post_text form-inline">
                    {{cart.quantity}}
                    <input type="submit" value="Thêm vào giỏ hàng" class="btn btn-success" style="margin-left:10px">
                </div>
            </form>
        </div>
    </div>
    {% endif%}
</div>
{% endblock %}

templates/shopOnlineApp/trangchu.html
{% extends "master.html" %}
{% block content %}
{% load staticfiles %}
<!-- Page Content -->
<div class="container">

  <!-- Jumbotron Header -->
  <header class="jumbotron my-4">
    <h1 class="display-3">A Warm Welcome!</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ipsa, ipsam, eligendi, in quo sunt
      possimus non incidunt odit vero aliquid similique quaerat nam nobis illo aspernatur vitae fugiat numquam repellat.
    </p>
    <a href="#" class="btn btn-primary btn-lg">Call to action!</a>
  </header>

  <!-- Page Features -->
  <div class="row text-center">
    {% if products %}
    {% for product in products %}
    <div class="col-lg-3 col-md-6 mb-4">
      <div class="card">
        <img class="card-img-top" src="{{product.image.url}}" alt="">
        <div class="card-body">
          <h4 class="card-title">{{product.name}}</h4>
          <p class="card-text">{{product.description}}</p>
        </div>
        <div class="card-footer">
          <a href="{% url 'shoponline:product_detail' product.id %}" class="btn btn-primary">Find Out More!</a>
        </div>
      </div>
    </div>
    {% endfor %}
    {% endif %}
  </div>
  <!-- /.row -->

</div>
<!-- /.container -->
{% endblock %}